default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: restromain_development
test:
  <<: *default
  database: restromain_test
  
production:
  <<: *default
  database: restromain_production
  username: restromain
  password: <%= ENV['RESTROMAIN_DATABASE_PASSWORD'] %>
